### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by CyrusSUEN**

### CODE REVIEW

**Comment by dhowe** [comment]
still wrong

**Comment by CyrusSUEN** [comment]
Could you point them out?

**Comment by dhowe** [comment]
why don't you try following your own instructions

**Comment by CyrusSUEN** [comment]
Just updated.
But RiTranslate cannot be found directly in the Contribution Manager of Processing. I can only resort to the step by step library installation

**Comment by dhowe** [comment]
still wrong -- which means to me that you didn't actually test it from scratch.
anyway, i've fixed it now

**Pull request merged**
